[pytest]
testpaths = tests
addopts =
    --cov=custom_components.tonies_box
    --cov-report=term-missing
    --cov-report=xml
    --timeout=20
    --asyncio-mode=auto
norecursedirs = .* build dist CVS _darcs {arch} *.egg virtualenv
